name: crackhash
services:
  manager:
    image: crackhash/manager:latest
    container_name: manager
    ports:
      - "8080:8080"
    networks:
      docker-inner-network:
        ipv4_address: 10.6.0.2

  worker:
    image: crackhash/worker:latest
    container_name: worker
    expose:
      - "8081:8081"
    networks:
      docker-inner-network:
        ipv4_address: 10.6.0.3

networks:
  docker-inner-network:
    ipam:
      driver: default
      config:
        - subnet: 10.6.0.0/24
          gateway: 10.6.0.1
